# Generated by Django 5.0.4 on 2024-12-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_agent_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='refresh_token',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
