# Generated by Django 5.0.4 on 2024-12-21 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_refresh_token'),
        ('app', '0003_remove_agency_agencymanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='service',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='superuser', to='app.service'),
        ),
    ]
