# Generated by Django 5.0.4 on 2024-12-22 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customuser_firstname_customuser_latsname_and_more'),
        ('app', '0008_alter_mission_status_alter_trip_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='agency',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to='app.agency'),
        ),
        migrations.AlterField(
            model_name='superuser',
            name='service',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superuser', to='app.service'),
        ),
    ]
