# Generated by Django 5.1.4 on 2024-12-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_admin_agency_alter_superuser_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='admin_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
