# Generated by Django 5.1.4 on 2024-12-31 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_latsname_customuser_lastname_and_more'),
        ('app', '0009_alter_agency_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superuser',
            name='service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superuser', to='app.service'),
        ),
    ]
