# Generated by Django 5.0.4 on 2024-12-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='agencymanager',
            new_name='agencyManager',
        ),
    ]
