# Generated by Django 5.0.4 on 2024-12-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_agencymanager_agency_agencymanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='agencyManager',
        ),
    ]
