# Generated by Django 5.0.4 on 2024-12-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_agency_agencymanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='mission',
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(default='yaounde', max_length=50),
            preserve_default=False,
        ),
    ]
