# Generated by Django 5.0.4 on 2024-12-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_service_mission_service_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mission',
            name='orderNumber',
            field=models.CharField(default='12345', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
