# Generated by Django 5.0.4 on 2024-12-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_trip_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='is_validated',
        ),
        migrations.AlterField(
            model_name='mission',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('in creation', 'In Creation'), ('approved', 'Approved'), ('in progress', 'In Progress'), ('rejected', 'Rejected'), ('failure', 'Failure'), ('finish', 'Finish')], default='in creation', max_length=20),
        ),
    ]
